import fs from 'node:fs';
import path from 'node:path';
import { DIST, PUBLIC, SOURCE_METADATA_PATH } from './lib/paths.mjs';
import { loadRegistry, validateLibrary } from './lib/registry.mjs';

const registry = loadRegistry();
const failures = [];

validateRegistry();
validateLegacyAppAssetsRemoved();
validateLibraryPayloads();
validateSourceMetadata();
validateDistRoutes();

if (failures.length > 0) {
	console.error(failures.join('\n'));
	process.exit(1);
}

console.log(`Validated ${registry.libraries.length} libraries, static payloads, import maps, and dist routes.`);

function validateRegistry() {
	if (registry.libraries.length === 0) {
		failures.push('libraries.json: registry must contain at least one library.');
	}

	for (const library of registry.libraries) {
		for (const field of validateLibrary(library)) {
			failures.push(`libraries.json: ${library.name || '(unknown library)'} is missing ${field}.`);
		}
	}
}

function validateLegacyAppAssetsRemoved() {
	for (const relativePath of ['index.html', 'styles', 'scripts/library-gallery']) {
		const staticPath = path.join(PUBLIC, relativePath);
		if (fs.existsSync(staticPath)) {
			failures.push(`public/${relativePath}: app-owned assets must be generated by Vite, not kept in public/.`);
		}
	}
}

function validateLibraryPayloads() {
	const expectedImports = Object.fromEntries(
		registry.libraries.map((library) => [library.name, `../vendor/${library.name}/index.js`])
	);

	for (const library of registry.libraries) {
		const libraryDir = path.join(PUBLIC, library.folder);
		const manifestPath = path.join(libraryDir, 'manifest.json');
		const sketchHtmlPath = path.join(libraryDir, 'sketch.html');
		const vendorPath = path.join(PUBLIC, 'vendor', library.name, 'index.js');

		if (fs.existsSync(path.join(libraryDir, 'index.html'))) {
			failures.push(`public/${library.folder}/index.html: library index pages must be generated into dist/.`);
		}
		if (!fs.existsSync(manifestPath)) failures.push(`public/${library.folder}/manifest.json: manifest is missing.`);
		if (!fs.existsSync(sketchHtmlPath))
			failures.push(`public/${library.folder}/sketch.html: sketch runner is missing.`);
		if (!fs.existsSync(vendorPath))
			failures.push(`public/vendor/${library.name}/index.js: vendor bundle is missing.`);
		if (fs.existsSync(path.join(libraryDir, 'scripts', 'gallery'))) {
			failures.push(
				`public/${library.folder}/scripts/gallery: stale source-local gallery runtime must not be synced.`
			);
		}

		if (fs.existsSync(manifestPath)) {
			validateManifestExamples(library.folder, manifestPath);
		}

		if (fs.existsSync(sketchHtmlPath)) {
			validateImportMap(library.folder, sketchHtmlPath, expectedImports);
		}
	}
}

function validateManifestExamples(libraryFolder, manifestPath) {
	try {
		const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
		const examples = collectExamples(manifest);

		if (examples.length === 0) {
			failures.push(`public/${libraryFolder}/manifest.json: manifest contains no examples.`);
		}

		for (const example of examples) {
			const examplePath = getExamplePath(example.sourceFile);
			const sketchPath = path.join(PUBLIC, libraryFolder, examplePath, 'sketch.js');
			if (!fs.existsSync(sketchPath)) {
				failures.push(`public/${libraryFolder}/manifest.json: missing sketch for ${example.sourceFile}.`);
			}
		}
	} catch (error) {
		failures.push(`public/${libraryFolder}/manifest.json: ${error.message}`);
	}
}

function collectExamples(manifest) {
	if (!Array.isArray(manifest?.groups)) {
		throw new Error('manifest is missing a groups array.');
	}

	return manifest.groups.flatMap((group) => {
		if (Array.isArray(group.subgroups)) {
			return group.subgroups.flatMap((subgroup) => subgroup.examples || []);
		}
		return group.examples || [];
	});
}

function getExamplePath(sourceFile) {
	if (typeof sourceFile !== 'string' || !sourceFile.startsWith('examples/') || !sourceFile.endsWith('/sketch.js')) {
		throw new Error(`Invalid example source file: ${sourceFile}`);
	}

	const examplePath = sourceFile.slice('examples/'.length, -'/sketch.js'.length);
	const segments = examplePath.split('/');
	const isValid =
		segments.length > 0 &&
		segments.every(
			(segment) => segment.length > 0 && segment !== '.' && segment !== '..' && /^[A-Za-z0-9_.-]+$/.test(segment)
		);

	if (!isValid) {
		throw new Error(`Invalid example path: ${examplePath}`);
	}

	return examplePath;
}

function validateImportMap(libraryFolder, sketchHtmlPath, expectedImports) {
	const html = fs.readFileSync(sketchHtmlPath, 'utf8');
	if (html.includes('"/vendor/')) {
		failures.push(`public/${libraryFolder}/sketch.html: import map must not use root-absolute /vendor paths.`);
	}

	const match = html.match(/<script type="importmap">([\s\S]*?)<\/script>/);
	if (!match) {
		failures.push(`public/${libraryFolder}/sketch.html: import map is missing.`);
		return;
	}

	try {
		const importMap = JSON.parse(match[1]);
		for (const [name, expectedPath] of Object.entries(expectedImports)) {
			if (importMap.imports?.[name] !== expectedPath) {
				failures.push(
					`public/${libraryFolder}/sketch.html: import map must map "${name}" to "${expectedPath}".`
				);
			}
		}
	} catch (error) {
		failures.push(`public/${libraryFolder}/sketch.html: import map contains invalid JSON (${error.message}).`);
	}
}

function validateSourceMetadata() {
	if (!fs.existsSync(SOURCE_METADATA_PATH)) {
		failures.push('public/source-metadata.json: source metadata is missing.');
		return;
	}

	const metadata = JSON.parse(fs.readFileSync(SOURCE_METADATA_PATH, 'utf8'));
	const entries = new Map((metadata.libraries || []).map((entry) => [entry.name, entry]));

	for (const library of registry.libraries) {
		const entry = entries.get(library.name);
		if (!entry) {
			failures.push(`public/source-metadata.json: missing source metadata for ${library.name}.`);
			continue;
		}
		for (const field of ['repository', 'ref', 'prepare', 'commit', 'examples', 'bundle', 'sketchCount']) {
			if (!entry[field] && entry[field] !== 0) {
				failures.push(`public/source-metadata.json: ${library.name} metadata is missing ${field}.`);
			}
		}
	}
}

function validateDistRoutes() {
	const rootIndex = path.join(DIST, 'index.html');
	if (!fs.existsSync(rootIndex)) {
		failures.push('dist/index.html: app shell is missing. Run npm run build first.');
	}

	for (const library of registry.libraries) {
		const routeIndex = path.join(DIST, library.folder, 'index.html');
		if (!fs.existsSync(routeIndex)) {
			failures.push(`dist/${library.folder}/index.html: library route app shell is missing.`);
		}
	}
}
